name: flutterfitapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^13.0.0
  oauth2_client: ^3.0.0
  uni_links: ^0.5.1
  http: ^1.3.0
  google_sign_in: ^6.1.0
  google_sign_in_web: ^0.12.1
  flutter_signin_button: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_secure_storage: ^8.0.0
  logger: ^2.0.2
  web: ^0.5.0
  url_launcher: ^6.2.6
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_svg: ^2.1.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/

